version: '3'

x-logging: &default-logging
  options:
    max-size: "100m"
    max-file: "5"
  driver: json-file

networks:
  zrb:
    name: zrb
    external: true

services:

  kebab-zrb-app-name:
    image: ${IMAGE:-zrbMetaBaseImage}
    logging: *default-logging
    container_name: ${CONTAINER_PREFIX:-my}-kebab-zrb-app-name
    hostname: kebab-zrb-app-name
    environment:
    - APP_PORT=${APP_PORT:-8080}
    - APP_MESSAGE=${APP_MESSAGE}
    ports:
    - "${HOST_PORT:-8080}:${APP_PORT:-8080}"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://localhost:${APP_PORT:-8080}/ || exit 1"]
      interval: 5s
      timeout: 1s
      retries: 30
    networks:
      - zrb