import pytest

from zrb.config.config import CFG


def test_config_properties_access():
    # Access all properties to boost coverage
    # LLM properties
    # _ = CFG.LLM_PROVIDER # Removed
    _ = CFG.LLM_MODEL
    _ = CFG.LLM_BASE_URL
    _ = CFG.LLM_API_KEY
    _ = CFG.LLM_MAX_REQUEST_PER_MINUTE
    _ = CFG.LLM_MAX_TOKEN_PER_MINUTE
    _ = CFG.LLM_MAX_TOKEN_PER_REQUEST
    _ = CFG.LLM_THROTTLE_SLEEP
    _ = CFG.LLM_HISTORY_SUMMARIZATION_TOKEN_THRESHOLD
    _ = CFG.LLM_HISTORY_SUMMARIZATION_WINDOW
    _ = CFG.LLM_REPO_ANALYSIS_EXTRACTION_TOKEN_THRESHOLD
    _ = CFG.LLM_REPO_ANALYSIS_SUMMARIZATION_TOKEN_THRESHOLD
    _ = CFG.LLM_FILE_ANALYSIS_TOKEN_THRESHOLD
    _ = CFG.LLM_ASSISTANT_NAME
    _ = CFG.LLM_ASSISTANT_JARGON
    _ = CFG.LLM_ASSISTANT_ASCII_ART
    _ = CFG.LLM_PLUGIN_DIRS
    _ = CFG.LLM_SMALL_MODEL
    _ = CFG.LLM_HISTORY_DIR
    _ = CFG.LLM_NOTE_FILE

    # RAG properties
    _ = CFG.RAG_EMBEDDING_API_KEY
    _ = CFG.RAG_EMBEDDING_BASE_URL
    _ = CFG.RAG_EMBEDDING_MODEL
    _ = CFG.RAG_CHUNK_SIZE
    _ = CFG.RAG_OVERLAP
    _ = CFG.RAG_MAX_RESULT_COUNT

    # Web properties
    _ = CFG.WEB_CSS_PATH
    _ = CFG.WEB_JS_PATH
    _ = CFG.WEB_FAVICON_PATH
    _ = CFG.WEB_COLOR
    _ = CFG.WEB_HTTP_PORT
    _ = CFG.WEB_GUEST_USERNAME
    _ = CFG.WEB_SUPER_ADMIN_USERNAME
    _ = CFG.WEB_SUPER_ADMIN_PASSWORD
    _ = CFG.WEB_ACCESS_TOKEN_COOKIE_NAME
    _ = CFG.WEB_REFRESH_TOKEN_COOKIE_NAME
    _ = CFG.WEB_SECRET_KEY
    _ = CFG.WEB_ENABLE_AUTH
    _ = CFG.WEB_AUTH_ACCESS_TOKEN_EXPIRE_MINUTES
    _ = CFG.WEB_AUTH_REFRESH_TOKEN_EXPIRE_MINUTES
    _ = CFG.WEB_TITLE
    _ = CFG.WEB_JARGON
    _ = CFG.WEB_HOMEPAGE_INTRO

    # Other properties
    _ = CFG.ENV_PREFIX
    _ = CFG.DEFAULT_SHELL
    _ = CFG.DEFAULT_EDITOR
    _ = CFG.DIFF_EDIT_COMMAND_TPL
    _ = CFG.INIT_MODULES
    _ = CFG.INIT_SCRIPTS
    _ = CFG.INIT_FILE_NAME
    _ = CFG.ROOT_GROUP_NAME
    _ = CFG.ROOT_GROUP_DESCRIPTION
    _ = CFG.LOGGING_LEVEL
    _ = CFG.SESSION_LOG_DIR
    _ = CFG.TODO_DIR
    _ = CFG.TODO_VISUAL_FILTER
    _ = CFG.TODO_RETENTION
    _ = CFG.VERSION
    _ = CFG.BANNER
    _ = CFG.SERPAPI_KEY

    # UI Commands
    _ = CFG.LLM_UI_COMMAND_ATTACH
    # _ = CFG.LLM_UI_COMMAND_CLEAR_HISTORY # Removed
    _ = CFG.LLM_UI_COMMAND_EXIT
    _ = CFG.LLM_UI_COMMAND_LOAD
    _ = CFG.LLM_UI_COMMAND_YOLO_TOGGLE
    _ = CFG.LLM_UI_COMMAND_REDIRECT_OUTPUT
    _ = CFG.LLM_UI_COMMAND_EXEC
    _ = CFG.LLM_UI_COMMAND_SET_MODEL
