version: '3'

x-logging: &default-logging
  options:
    max-size: "100m"
    max-file: "5"
  driver: json-file

networks:
  zrb:
    name: zrb
    external: true

services:

  kebab-zrb-task-name:
    build: image
    image: ${IMAGE:-kebab-zrb-task-name}
    logging: *default-logging
    container_name: ${CONTAINER_PREFIX:-my}-kebab-zrb-task-name
    hostname: kebab-zrb-task-name
    environment:
      APP_MESSAGE: '${MESSAGE:-Hello, world!}'
      APP_PORT: '${CONTAINER_PORT:-8080}'
    ports:
    - ${HOST_PORT:-8080}:${CONTAINER_PORT:-8080}
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://localhost:${APP_PORT:-8080}/ || exit 1"]
      interval: 5s
      timeout: 1s
      retries: 30
    networks:
      - zrb