annotations:
  artifacthub.io/images: |
    - name: redpanda
      image: docker.redpanda.com/redpandadata/console:v2.4.3
  artifacthub.io/license: Apache-2.0
  artifacthub.io/links: |
    - name: Documentation
      url: https://docs.redpanda.com
    - name: "Helm (>= 3.6.0)"
      url: https://helm.sh/docs/intro/install/
apiVersion: v2
appVersion: v2.4.3
description: Helm chart to deploy Redpanda Console.
icon: https://images.ctfassets.net/paqvtpyf8rwu/3cYHw5UzhXCbKuR24GDFGO/73fb682e6157d11c10d5b2b5da1d5af0/skate-stand-panda.svg
maintainers:
- name: redpanda-data
  url: https://github.com/orgs/redpanda-data/people
name: console
sources:
- https://github.com/redpanda-data/helm-charts
type: application
version: 0.7.21
