annotations:
  artifacthub.io/images: |
    - name: connectors
      image: docker.redpanda.com/redpandadata/connectors:v1.0.6
    - name: rpk
      image: docker.redpanda.com/redpandadata/redpanda:latest
  artifacthub.io/license: Apache-2.0
  artifacthub.io/links: |
    - name: Documentation
      url: https://docs.redpanda.com
    - name: "Helm (>= 3.6.0)"
      url: https://helm.sh/docs/intro/install/
apiVersion: v2
appVersion: v1.0.6
description: Redpanda managed Connectors helm chart
icon: https://images.ctfassets.net/paqvtpyf8rwu/3cYHw5UzhXCbKuR24GDFGO/73fb682e6157d11c10d5b2b5da1d5af0/skate-stand-panda.svg
kubeVersion: ^1.21.0-0
maintainers:
- name: redpanda-data
  url: https://github.com/orgs/redpanda-data/people
name: connectors
sources:
- https://github.com/redpanda-data/helm-charts
type: application
version: 0.1.10
