{{- if (include "clickhouse.createSecret" .) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "clickhouse.secretName" . }}
type: Opaque
data:
  {{ include "clickhouse.secretPasswordKey" . }}: {{ .Values.externalClickhouse.password | b64enc | quote }}
{{- end }}
