apiVersion: v2
appVersion: 0.40.0
dependencies:
- condition: clickhouse.enabled
  name: clickhouse
  repository: https://signoz.github.io/charts
  version: 23.13.0
- condition: k8s-infra.enabled
  name: k8s-infra
  repository: https://signoz.github.io/charts
  version: 0.11.4
- condition: cert-manager.enabled
  name: cert-manager
  repository: https://charts.jetstack.io
  version: 1.9.1
- condition: ingress-nginx.enabled
  name: ingress-nginx
  repository: https://kubernetes.github.io/ingress-nginx
  version: 4.3.0
- condition: minio.enabled
  name: minio
  repository: https://charts.min.io
  version: 4.0.9
- condition: keycloak.enabled
  name: keycloak
  repository: https://charts.bitnami.com/bitnami
  version: 10.1.5
description: SigNoz Observability Platform Helm Chart
home: https://signoz.io/
icon: https://signoz.io/img/SigNozLogo-orange.svg
keywords:
- SigNoz
- opentelemetry
- apm
- monitoring
- distributed tracing
- distributed logging
maintainers:
- email: hello@signoz.io
  name: SigNoz
  url: https://signoz.io
- email: prashant@signoz.io
  name: prashant-shahi
  url: https://prashantshahi.dev
name: signoz
sources:
- https://github.com/signoz/charts
- https://github.com/signoz/signoz
- https://github.com/signoz/alertmanager
- https://github.com/signoz/signoz-otel-collector
type: application
version: 0.36.0
